# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction.

What are the prerequisites, for both knowledge and e.g. software setup?

This will be bullet points to expand on further on the user guide.

-   Knowledge:

    -   R coding knowledge

    -   Linear Regression

    -   Some Linear Algebra

    -   Some Knowledge of Statistic (Knots, etc)

-   Software Setup:

    -   Need a computer or laptop capable of coding

    -   Download R for statistical computing

    -   Download RStudio (not required but very helpful)

    -   In R open an R Script

    -   Type install.packages("splines") and run

    -   Type install.packages("tidyverse") and run

    -   Type library(splines) and run

    -   Type library(tidyverse) and run

    -   Maybe a data set you want to use splines on

::: callout-note

It's fine to say that your user guide assumes a basic knowledge of R and the tidyverse and how to use an IDE such as RStudio. Then you don't have to describe installing R/Rstudio/tidyverse and can just start at installing splines.

Having a dataset to use splines on is more important -- as is specifying what you need for such a dataset -- a continuous? predictor and response, etc.

Think more carefully about why someone would want to use splines over other, more structured models...

:::

What are the basic requirements for any data that the method is used on? - Are missing values allowed? - Should the data be confined within a certain range? - Does the data have to be approximately normally distributed?

-   Missing or NA values will not work with splines.

-   Data needs to have some sort of variability to it.

-   Any range of values works.

    -   Might be hard to see the splines with very large outliers.

-   Data does not have to be normally distributed.

-   Won't work well with binary data.

-   Works best with scatter plots and line plots.

::: callout-note

I'm not sure what type of data a scatter plot or line plot is... yes, there are some types of data that are more conducive to that type of plots, and those are also better for splines, but you need to articulate what those are, specifically, in terms of the data and not how it is visualized.

:::

What are the basic components of the task? - Outline these in a bit more detail

-   Splines are smooth curves that follow trends in data to try to help explain the data points better.

-   A B-spline is a linear combination of basis functions that are explained over a set of knots. Knots are the places where splines join based on the data. The more knots you have for a spline the "wigglier" the splines are. Knots are useful to let the curve follow the data better at its trends. Degrees of freedom for the model also explain "wiggliness".

::: callout-note

Feel free to illustrate the effect of these knots with sketches/cartoons.

:::

-   Need a data set or simulated data to use the splines on.

-   Need to get a linear model from the data

-   Make a prediction matrix of the data for the splines

-   plot the spline over the data set before to see the trend of the data.

What decisions does the user need to be prepared to make on the fly?

-   Be prepared to do data cleaning to get rid of NAs.

-   Be prepared to "debug" the code that might not work for them.

What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?

-   The basics of what is needed to find the splines.

-   The knowledge of what is being talked about before.

## Additional Guidance

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic).

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. This document should remain as an appendix to your main report.
