# Topic

Pick some subset of the information covered in your annual review article that you are interested in exploring in more detail. 

- How to use B-splines to fit a smooth curve on messy data.

Identify the scope of your user guide - what will you cover? Specific software packages? When to use or not to use a specific technique?

- How B-splines are used to smooth data using the mgcv and splines package.
- How to make messy and choppy data have better data curves to help show underlying data trends better.
- How lowess smoothing functions and spline smoothing looks different.


::: callout-note
# Comments/suggestions

I need quite a bit more detail here to ensure that you're set up for success. Define your scope - what type of splines? Will you compare to LOWESS smooths? Is the focus on penalized spline regression, or just smoothing splines? 

"Fixing" messy data isn't something splines can do, so I'd like you to try to reframe this and resubmit so that I can help steer you on a successful completion path. 

:::